language: python
python:
    - 2.7
    - 3.4
    - 3.5
install:
    - pip install .
    - make devenv
script:
    - make test
    - make style
after_success:
    - bash <(curl -s https://codecov.io/bash)
